dm_shopmode_cat_type:
    resource: "@DMShopmodeBundle/Controller/CatTypeController.php"
    type:     annotation

dmdb_maintenance:
    resource: "@DMDBMaintenanceBundle/Controller/"
    prefix: /maint/
    type:   annotation

dm_shopmode:
    resource: "@DMShopmodeBundle/Controller/"
    prefix:   /shop/
    type: annotation
    
app:
    resource: '@AppBundle/Controller/'
    prefix:   /
    type: annotation
