# !!! A retirer - obsolète
#dm_shopmode:
#    resource: "@DMShopmodeBundle/Resources/config/routing.yml"
#    prefix:   /shop/

dm_shopmode:
    resource: "@DMShopmodeBundle/Controller/"
    prefix:   /shop/
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
