dm_user:
    resource: "@DMUserBundle/Controller/"
    type:     annotation
    prefix:   /

dm_shopmode_articles:
    resource: "@DMShopmodeBundle/Controller/ArticlesController.php"
    type:     annotation

dm_shopmode_articles_categories:
    resource: "@DMShopmodeBundle/Controller/ArticlesCategoriesController.php"
    type:     annotation

dm_shopmode_cat_type:
    resource: "@DMShopmodeBundle/Controller/CatTypeController.php"
    type:     annotation

dmdb_maintenance:
    resource: "@DMDBMaintenanceBundle/Controller/"
    prefix: /maint/
    type:   annotation

dm_shopmode:
    resource: "@DMShopmodeBundle/Controller/ShopController.php"
    prefix:   /shop/
    type: annotation
    
app:
    resource: '@AppBundle/Controller/'
    prefix:   /
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile