<?php

namespace DM\ShopmodeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatTypeRepository extends EntityRepository
{
  public function findAllOrderedByOrdre() {
    return $this->findBy([], ['ordre' => 'ASC']);
  }
  // ------------------------

  // ========================================
}
